version: '3.4'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=example
    ports:
      - 27017:27017

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
    ports:
      - 5432:5432
