features:
  transactionProcessor:
    maxLookBehind: 100
chainId: T
contracts:
  swap: erd1qqqqqqqqqqqqqpgq8cer8c44z7um52465gt0pc833lcspdu64juslpuklj
security:
  jwtSecret: ''
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
keepAlive:
  enabled: true
  timeout:
    downstream: 61000
    upstream: 60000
useCachingInterceptor: false
nativeAuthTtl: 2592000 # 30 days
dapp:
  environment: testnet
  walletConnectV2ProjectId: 9c1851da02319e1280cbbf2de5d8ee46
  apiTimeout: 6000
  updateRefreshRate: 60000
